---
title: "Projet d'Analyse des données"
author: "Bill Yehouenou"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
getwd()
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = NA)
```

# 1. Création de la fonction AFC
```{r definition de la fonction afc}
AFC <- function(N){
  Nind <- sum(N)
  #a. calcul des métriques
  Di <- diag(prop.table(rowSums(N)))
  Dj <- diag(prop.table(colSums(N)))
  #calculs des inverses et autres
  DiInv <- diag(1/prop.table(rowSums(N)))
  DjInv <- diag(1/prop.table(colSums(N)))
  #calcul de Dj^{1/2} et son inverse
  DjDemi <- diag(sqrt(colSums(prop.table(N))))
  DjDemiInv <- diag(1/sqrt(colSums(prop.table(N))))
  #b. tableau des frequences Z
  vec_Z <- unlist(prop.table(N))
  Z <- matrix(vec_Z, nrow(N), ncol(N))
  #c. matrice des écarts a l'indépendance X
  X <- (DiInv %*% Z %*% DjInv) - 1
  #d. calcul de la matrice V
  V <- t(X) %*% Di %*% X
  #e. vecteurs propres et mise en place de la matrice normee A
  DjDemiVDjDemi <- DjDemi %*% V %*% DjDemi
  #decomposition en vecteurs et valeurs propres
  ll <- eigen(DjDemiVDjDemi, symmetric=TRUE)
  A <- DjDemiInv %*% ll$vectors
  #f. determination des vecteurs propres DI-normes par la formule de transition
  C <- Z %*% Dj %*% A %*% ll$values #lambda_k = matrice des valeurs et vecteur du pourcentage d'inertie de chaque axe
  #g. calcul du vecteur qui stocke le pourcentage d'inertie
  inertieBrute <- ll$values
  vec_prct_inertie <- as.vector(inertieBrute*100/sum(inertieBrute))
  #h. calcul des coordonnees des lignes et colones
  A_tilde <- t(Z) %*% Di %*% C
  C_tilde <- C %*% ll$values
  #i. liste des resultats
  resu <- list(vec_prct_inertie,A,C,A_tilde,C_tilde)
  return(resu)
}
```

# 2. Graphique des lignes
```{r graphique des lignes}
graph_lignes <- function(N){
  afc_table <- AFC(N)
  coord_lignes <- afc_table[[5]]
  par(pty = "s")
  graph_ligne <- plot(coord_lignes,pch=15,cex=.5,
                      xlab="Coordonnées sur axe 1",ylab="Coordonnées sur axe 2",
                      main="Coordonnées des lignes du tableau de contingence")
  abline(h=0,v=0,lty=15) #origine du graphique (0,0) et point moyen
  return(graph_ligne)
}
```

# 3. Graphique des colonnes
```{r graphique des colonnes}
graph_colones <- function(N){
  afc_table <- AFC(N)
  coord_colonnes <- afc_table[[4]]
  par(pty = "s")
  graph_colonne <- plot(coord_colonnes,pch=16,cex=.5,col='red',
                      xlab="Coordonnées sur axe 1",ylab="Coordonnées sur axe 2",
                      main="Coordonnées des colonnes du tableau de contingence")
  abline(h=0,v=0,lty=15) #origine du graphique (0,0) et point moyen
  return(graph_colonne)
}
```

# 4. Test des fonctions avec la table _bordeaux_
```{r test des fonctions}
bordeaux <- read.csv("bordeaux.csv", sep = ";")
AFC(bordeaux)
graph_lignes(bordeaux)
graph_colones(bordeaux)
```
